begin;
set local role postgres;
create extension if not exists pgtap with schema extensions;
set local search_path = public, extensions;
select plan(24);
select is(has_function_privilege('anon','api.admin_session_create(text,text)','EXECUTE'),false,'anonymous cannot mint admin sessions');
select is(has_function_privilege('authenticated','api.admin_session_create(text,text)','EXECUTE'),false,'app user cannot mint admin sessions');
select is(has_function_privilege('authenticated','api.admin_session_valid(text,text)','EXECUTE'),false,'app user cannot inspect admin tokens');
select is(has_function_privilege('authenticated','api.admin_session_revoke(text)','EXECUTE'),false,'app user cannot revoke admin sessions');
select is(has_function_privilege('authenticated','api.admin_login_attempt(boolean)','EXECUTE'),false,'app user cannot reset admin login limit');
select is(has_function_privilege('authenticated','api.admin_deleted_detail(uuid)','EXECUTE'),false,'app user cannot read archived details');
select is(has_function_privilege('authenticated','api.admin_deleted_data(timestamptz,uuid,text)','EXECUTE'),false,'app user cannot list archived data');
select is(has_table_privilege('authenticated','private.admin_sessions','SELECT'),false,'app user cannot read admin session hashes');
select is(has_table_privilege('anon','private.admin_sessions','SELECT'),false,'anonymous cannot read admin session hashes');
select is(has_function_privilege('service_role','api.admin_session_valid(text,text)','EXECUTE'),true,'backend can validate admin sessions');
select is((select count(*)::integer from pg_policies where schemaname='storage' and tablename='objects' and policyname='deleted_data_admin_read'),0,'old email-only storage read policy is removed');
select is(api.admin_session_valid(repeat('a',64),repeat('b',64)),false,'unknown token rejected');
select lives_ok($$select api.admin_session_create(repeat('a',64),repeat('b',64))$$,'backend creates admin session');
select is(api.admin_session_valid(repeat('a',64),repeat('b',64)),true,'matching token and credentials are valid');
select is(api.admin_session_valid(repeat('c',64),repeat('b',64)),false,'wrong token rejected');
select is(api.admin_session_valid(repeat('a',64),repeat('c',64)),false,'credential rotation invalidates old session');
update private.admin_sessions set expires_at=now()-interval '1 second' where token_hash=repeat('a',64);
select is(api.admin_session_valid(repeat('a',64),repeat('b',64)),false,'expired session rejected');
update private.admin_sessions set expires_at=now()+interval '1 hour' where token_hash=repeat('a',64);
select api.admin_session_revoke(repeat('a',64));
select is(api.admin_session_valid(repeat('a',64),repeat('b',64)),false,'logged-out token cannot be replayed');
update private.admin_login_attempts set failures=0,window_started_at=now();
select is(api.admin_login_attempt(true),true,'valid credentials reset a non-exhausted limit');
select is(api.admin_login_attempt(false),true,'first incorrect attempt counted');
select api.admin_login_attempt(false) from generate_series(1,4);
select is(api.admin_login_attempt(false),false,'sixth incorrect attempt is rate limited');
select is(api.admin_login_attempt(true),false,'correct credentials cannot bypass the exhausted budget');
update private.admin_login_attempts set window_started_at=now()-interval '16 minutes';
select is(api.admin_login_attempt(false),true,'new window after expiry');
update private.admin_login_attempts set failures=10,window_started_at=now()-interval '16 minutes';
select is(api.admin_login_attempt(false),true,'rate limit window expires');
select * from finish();
rollback;
